### PR TITLE
Upgrade from 5.1 to 5.2

### PR DESCRIPTION
**Pull request by petericebear**

### CODE REVIEW

**Comment by hiddeco** [comment]
@petericebear thanks for your hard work `5.2` and `5.3` are now available :tada:

**Comment by petericebear** [comment]
Thank you, it would be nice to add a Credits or something.
I will look into some more tests as well for the functionality and the Laravel-api wrapper.

Maybe you can look into a good example for the CentOS based Unattended example.

**Comment by hiddeco** [comment]
@petericebear: will make a contributors credit list later today in the `readme.md` :smile: 

Moaking SOAP for test purposes is a crazy ass nightmare but be my guest.

**Comment by hiddeco** [comment]
@petericebear: there you go :wink: https://github.com/hiddeco/transip#contributors

**Pull request merged**
