### PR TITLE
Added installOperatingSystemUnattended functionality

### PR DESCRIPTION
**Pull request by petericebear**

### CODE REVIEW

**Comment by hiddeco** [comment]
Can you confirm this is the only new feature in the `5.1` -> `5.2` release of the API?

**Comment by petericebear** [comment]
If you download the zip, you can see that the version is now 5.3 ;-) this is the only newly added feature that I know of and found, since I requested this feature by TransIP team.

**Comment by hiddeco** [comment]
@petericebear ah fuck, that means I've to release 2 versions. Let me take a look what `5.2` offers more than the current wrapper so I can release them in sync. Or be my guest and make a list of the changes if you've time. :-)

**Comment by petericebear** [comment]
I will try to make some time free for it, better to make one package good, than creating a package myself for TransIP, I think maybe thursday. What I believe are minor changes mostly in the VPS part.

**Comment by hiddeco** [comment]
@petericebear did a `diff` on the `5.1` and `5.2` zip and there are indeed some added features to the VPS functionalities. That's it as far as my quick look did go. 

I also propose a namespace to `TransIP` instead of `HiddeCo\TransIP` and release tags equal to the version number of the API.

Any help is appreciated :+1:.

**Comment by petericebear** [comment]
I think that is a neat solution of the namespace proposal. I certainly think they will appreciate it.
What is your suggestion, implement everything in this Pull Request?

**Comment by hiddeco** [comment]
@petericebear: please make the `5.2` adjustments in a new pull request. That way I can put a different version tag on both commits :+1:

**Comment by petericebear** [comment]
Okido will do

**Pull request merged**
